"""add solved to puzzle attempts

Revision ID: 1d193921a92b
Revises: a5e0cfae5659
Create Date: 2026-08-28 09:29:31.587006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d193921a92b'
down_revision: Union[str, Sequence[str], None] = 'a5e0cfae5659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle_attempts', sa.Column('solved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle_attempts', 'solved')
    # ### end Alembic commands ###
