"""add attempt completion status

Revision ID: 1f921529d6f4
Revises: 9aa67056ea40
Create Date: 2026-08-27 14:03:52.107872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f921529d6f4'
down_revision: Union[str, Sequence[str], None] = '9aa67056ea40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle_attempts', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle_attempts', 'completed')
    # ### end Alembic commands ###
