"""add attempts count

Revision ID: 9aa67056ea40
Revises: 5adf042f5a70
Create Date: 2026-08-27 13:55:45.135307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa67056ea40'
down_revision: Union[str, Sequence[str], None] = '5adf042f5a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle_attempts', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle_attempts', 'attempts')
    # ### end Alembic commands ###
