"""add admin flag to users

Revision ID: a5e0cfae5659
Revises: edc688e3a352
Create Date: 2026-08-28 00:31:59.146631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e0cfae5659'
down_revision: Union[str, Sequence[str], None] = 'edc688e3a352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column(
            'is_admin',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        )
    )

    op.alter_column(
        'users',
        'is_admin',
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
